### ISSUE TITLE
release connection

### ISSUE THREAD

**Issue by skydiablo** [szado/reactphp-connection-pool#2]
hi,
how can i decrease the connection usage-counter [check out](https://github.com/szado/reactphp-connection-pool/blob/a0a089d93f2aa4e446358c5e10bed89520d87e4e/src/ConnectionSelectors/UsageConnectionSelector.php#L39) ???

is it possible to block an connection to handle an SQL transactions? so no other `SELECT` or something else with an implicit `COMMIT ` will break an transaction?

regards, volker.

**Comment by szado** [comment]
Hi,

1) You can make your own version of `UsageConnectionSelector` and add this
functionality. Then pass your new selector class in pool constructor.

2) Yes, sure. If you want to block the adapter from selecting it, just
return proper state from `getState()` method (`ConnectionState::Busy`).

**Comment by skydiablo** [comment]
thx
